use gpui::actions;

actions!(
    aster,
    [
        About,
        CloseWindow,
        Copy,
        Cut,
        Find,
        FindNext,
        FindPrevious,
        FontSizeIncrease,
        FontSizeDecrease,
        FontSizeReset,
        NewFile,
        OpenFile,
        OutlinePositionLeft,
        OutlinePositionRight,
        Paste,
        Quit,
        Redo,
        SaveFile,
        SaveFileAs,
        SelectAll,
        ThemeAyuDark,
        ThemeAyuLight,
        ThemeAyuMirage,
        ToggleOutline,
        TogglePreview,
        Undo,
    ]
);
